export const environment = {
  production: false,
  IsProduction: false,
  APP_TITLE: 'Phần Mềm Kiểm Tra Chất Lượng',
  APP_CODE: 'KTTV',
  // APP_API_URL: 'https://localhost:44380',
  // APP_API_UPLOAD_URL: 'https://localhost:44380',
  CheckAuthen: true,
  IsSystem: true,
  StoragePath: '/usr/share/vitam',
  OCR_FOLDER: 'OCR',
  OCR_TEMPLATE_FOLDER: 'OCR/template',
  ClientSigningBaseUrl: 'http://localhost:14423',
  NOTIFICATION_DELAY_TIME: 150000,
  URLLOGO: '../../../../assets/monre-logo.png',
  PROFILE_PDF_NO_DISPLAY: 'adss:signing:profile:001',
  PROFILE_CMS: 'adss:signing:profile:003',
  PROFILE_PDF_DISPLAY_BASIC: 'adss:signing:profile:001',
  PROFILE_PDF_DISPLAY_ADVANCED: 'adss:signing:profile:002',
  PROFILE_XML: 'adss:signing:profile:005',
  PROFILE_OFFICE: 'adss:signing:profile:008',
  IMPORT_DATA: 'ImportData',
};
export const UrlForRoles = [
  { Url: '/user', RoleCode: 'QLND' },
  { Url: '/navigation', RoleCode: 'QLDH' },
  { Url: '/group-role', RoleCode: 'QLNND' },
  { Url: '/organization', RoleCode: 'CCTT' },
  { Url: '/application', RoleCode: 'QLUD' },
  { Url: '/system-params', RoleCode: 'TSHT' },
  { Url: '/role', RoleCode: 'QLQ' },
];
