import { INavData } from '@coreui/angular';
import { faLeaf, faSearch } from '@fortawesome/free-solid-svg-icons';
export const navItems: any[] = [
  // {
  //   name: 'HOME',
  //   class : "HOME",
  //   url: '/',
  //   iconComponent: { name: 'cil-home'},
  // },
  // {
  //   name: 'FUNCTION',
  //   class : "FUNCTION",
  //   title: true
  // },
  {
    name: 'SYSTEM_MANAGEMENT',
    class: 'SYSTEM_MANAGEMENT',
    url: '/',
    Icon: 'fa fa-puzzle-piece',
    iconComponent: { name: 'cil-puzzle' },
    acive: false,
    children: [
      {
        name: 'USER',
        class: 'USER',
        url: '/user',
        acive: false,
        Icon: '',
      },
      {
        name: 'ORGANIZATION_STRUCTURE',
        class: 'ORGANIZATION_STRUCTURE',
        url: '/organization',
        acive: false,
        Icon: '',
      },
      {
        name: 'NAVIGATION_NAV',
        class: 'NAVIGATION_NAV',
        url: '/navigation',
        acive: false,
        Icon: '',
      },
      {
        name: 'CATALOG',
        class: 'CATALOG',
        url: '/catalog',
        acive: false,
        Icon: '',
      },
      {
        name: 'ROLE_NAV',
        class: 'ROLE_NAV',
        url: '/role',
        acive: false,
        Icon: '',
      },
      {
        name: 'STATES',
        class: 'STATES',
        url: '/states',
        acive: false,
        Icon: '',
      },
      {
        name: 'COMMAND',
        class: 'COMMAND',
        url: '/command',
        acive: false,
        Icon: '',
      },
      {
        name: 'APPLICATION',
        class: 'APPLICATION',
        url: '/application',
        Icon: '',
      },
      {
        name: 'GROUP_ROLE',
        class: 'GROUP_ROLE',
        url: '/group-role',
        acive: false,
        Icon: '',
      },
      {
        name: 'SYSTEM_PARAMS',
        class: 'SYSTEM_PARAMS',
        url: '/system-params',
        acive: false,
        Icon: '',
      },
      {
        name: 'PIPE_LINE',
        class: 'PIPELINE',
        url: '/pipe-line',
        acive: false,
        Icon: '',
      },
      {
        name: 'SPACE',
        class: 'SPACE',
        url: '/space',
        acive: false,
        Icon: '',
      },
      {
        name: 'SPACE_LOCATION',
        class: 'SPACE_LOCATION',
        url: '/space-location',
        acive: false,
        Icon: '',
      },
      {
        name: 'ARM_FOND',
        class: 'ARM_FOND',
        url: '/arm-fond',
        acive: false,
        Icon: '',
      },
      {
        name: 'ARM_FOND',
        class: 'ARM_FOND',
        url: '/import-record',
        acive: false,
        Icon: '',
      },
      {
        name: 'ARM_FOND',
        class: 'ARM_FOND',
        url: '/import-document',
        acive: false,
        Icon: '',
      },
    ],
  },
  {
    name: 'CATEGORY_MANAGEMENT',
    class: 'CATEGORY_MANAGEMENT',
    url: '/',
    Icon: 'fa fa-list-alt',
    iconComponent: { name: 'cil-cursor' },
    acive: false,
    children: [
      {
        name: 'COUNTRY',
        class: 'COUNTRY',
        url: '/country',
        acive: false,
        Icon: '',
      },
      {
        name: 'PROVINCE',
        class: 'PROVINCE',
        url: '/province',
        acive: false,
        Icon: '',
      },
      {
        name: 'DISTRICT',
        class: 'DISTRICT',
        url: '/district',
        acive: false,
        Icon: '',
      },
      {
        name: 'WARD',
        class: 'WARD',
        url: '/ward',
        acive: false,
        Icon: '',
      },
      {
        name: 'ETHNIC',
        class: 'ETHNIC',
        url: 'ethnic',
        acive: false,
        Icon: '',
      },
    ],
  },
  {
    name: 'STATISTICAL',
    class: 'STATISTICAL',
    iconComponent: { name: 'cil-notes' },
    acive: false,
    url: '/',
    Icon: 'fa fa-th-large',
    children: [
      {
        name: 'SYSTEM_LOG',
        url: 'system-log',
        class: 'SYSTEM_LOG',
        acive: false,
        Icon: '',
      },
    ],
  },
];
