export const navItems: any[] = [
  /* ================= QC1 ================= */
  {
    ApplicationId: 1,
    HasChild: true,
    IconClass: 'fa fa-sliders',
    IsSystem: true,
    RoleId: 0,
    NavigationId: 501,
    NavigationCode: 'QUALITY_QC1',
    NavigationName: 'Thiết lập kiểm tra QC1',
    NavigationNameEN: 'QUALITY_QC1',
    Order: 0,
    Status: 1,
    CreatedOnDate: '2025-10-04T00:00:00',
    LastModifiedOnDate: '2025-10-04T00:00:00',
    RightCodes: [],
    SubNavigation: [
      /* Khí tượng bề mặt */
      {
        ParentNavigationId: 501,
        ApplicationId: 1,
        HasChild: true,
        UrlRewrite: '',
        IconClass: 'fa fa-cloud',
        IsSystem: true,
        RoleId: 0,
        NavigationId: 511,
        NavigationCode: 'QC1_MET',
        NavigationName: 'Khí tượng bề mặt',
        NavigationNameEN: 'MET_SURFACE',
        Order: 0,
        Status: 1,
        RightCodes: [],
        SubNavigation: [
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/temperature',
            IconClass: 'fa fa-thermometer-half',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 512,
            NavigationCode: 'QC1_TEMP',
            NavigationName: 'Nhiệt độ',
            NavigationNameEN: 'TEMPERATURE',
            Order: 0,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/dewpoint',
            IconClass: 'fa fa-tint',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 513,
            NavigationCode: 'QC1_DEWPOINT',
            NavigationName: 'Nhiệt độ điểm sương',
            NavigationNameEN: 'DEW_POINT',
            Order: 1,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/wind',
            IconClass: 'fa fa-flag-o',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 514,
            NavigationCode: 'QC1_WIND',
            NavigationName: 'Gió',
            NavigationNameEN: 'WIND',
            Order: 2,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/pressure',
            IconClass: 'fa fa-compress',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 515,
            NavigationCode: 'QC1_PRESSURE',
            NavigationName: 'Khí áp',
            NavigationNameEN: 'PRESSURE',
            Order: 3,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/radiation',
            IconClass: 'fa fa-sun-o',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 516,
            NavigationCode: 'QC1_RADIATION',
            NavigationName: 'Bức xạ',
            NavigationNameEN: 'RADIATION',
            Order: 4,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/cloud',
            IconClass: 'fa fa-cloud-upload',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 517,
            NavigationCode: 'QC1_CLOUD',
            NavigationName: 'Mây',
            NavigationNameEN: 'CLOUD',
            Order: 5,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/visibility',
            IconClass: 'fa fa-eye',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 518,
            NavigationCode: 'QC1_VISIBILITY',
            NavigationName: 'Tầm nhìn ngang',
            NavigationNameEN: 'HORIZONTAL_VISIBILITY',
            Order: 6,
            Status: 1,
          },
          {
            ParentNavigationId: 511,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/raintime',
            IconClass: 'fa fa-clock-o',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 519,
            NavigationCode: 'QC1_RAIN_TIME',
            NavigationName: 'Thời gian mưa',
            NavigationNameEN: 'RAIN_DURATION',
            Order: 7,
            Status: 1,
          },
        ],
      },
      /* Thủy văn */
      {
        ParentNavigationId: 501,
        ApplicationId: 1,
        HasChild: true,
        UrlRewrite: '',
        IconClass: 'fa fa-tint',
        IsSystem: true,
        RoleId: 0,
        NavigationId: 521,
        NavigationCode: 'QC1_HYDRO',
        NavigationName: 'Thủy văn',
        NavigationNameEN: 'HYDROLOGY',
        Order: 1,
        Status: 1,
        RightCodes: [],
        SubNavigation: [
          {
            ParentNavigationId: 521,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/rain',
            IconClass: 'fa fa-umbrella',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 522,
            NavigationCode: 'QC1_RAIN',
            NavigationName: 'Mưa',
            NavigationNameEN: 'RAIN',
            Order: 0,
            Status: 1,
          },
          {
            ParentNavigationId: 521,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/waterlevel',
            IconClass: 'fa fa-bars',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 523,
            NavigationCode: 'QC1_WATER_LEVEL',
            NavigationName: 'Mực nước',
            NavigationNameEN: 'WATER_LEVEL',
            Order: 1,
            Status: 1,
          },
          {
            ParentNavigationId: 521,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/discharge',
            IconClass: 'fa fa-exchange',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 524,
            NavigationCode: 'QC1_DISCHARGE',
            NavigationName: 'Lưu lượng nước',
            NavigationNameEN: 'DISCHARGE',
            Order: 2,
            Status: 1,
          },
          {
            ParentNavigationId: 521,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc1/independent-rain',
            IconClass: 'fa fa-tint',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 525,
            NavigationCode: 'QC1_RAIN_INDEPENDENT',
            NavigationName: 'Mưa độc lập',
            NavigationNameEN: 'INDEPENDENT_RAIN',
            Order: 3,
            Status: 1,
          },
        ],
      },
    ],
  },

  /* ================= QC2 ================= */
  {
    ApplicationId: 1,
    HasChild: true,
    IconClass: 'fa fa-sliders',
    IsSystem: true,
    RoleId: 0,
    NavigationId: 530,
    NavigationCode: 'QUALITY_QC2',
    NavigationName: 'Thiết lập kiểm tra QC2',
    NavigationNameEN: 'QUALITY_QC2',
    Order: 1,
    Status: 1,
    CreatedOnDate: '2025-10-04T00:00:00',
    LastModifiedOnDate: '2025-10-04T00:00:00',
    RightCodes: [],
    SubNavigation: [
      {
        ParentNavigationId: 530,
        ApplicationId: 1,
        HasChild: true,
        UrlRewrite: '',
        IconClass: 'fa fa-cloud',
        IsSystem: true,
        RoleId: 0,
        NavigationId: 531,
        NavigationCode: 'QC2_MET',
        NavigationName: 'Khí tượng bề mặt',
        NavigationNameEN: 'MET_SURFACE',
        Order: 0,
        Status: 1,
        RightCodes: [],
        SubNavigation: [
          {
            ParentNavigationId: 531,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/temperature',
            IconClass: 'fa fa-thermometer-half',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 532,
            NavigationCode: 'QC2_TEMP',
            NavigationName: 'Nhiệt độ',
            NavigationNameEN: 'TEMPERATURE',
            Order: 0,
            Status: 1,
          },
          {
            ParentNavigationId: 531,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/dewpoint',
            IconClass: 'fa fa-tint',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 533,
            NavigationCode: 'QC2_DEWPOINT',
            NavigationName: 'Nhiệt độ điểm sương',
            NavigationNameEN: 'DEW_POINT',
            Order: 1,
            Status: 1,
          },
          {
            ParentNavigationId: 531,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/wind',
            IconClass: 'fa fa-flag-o',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 534,
            NavigationCode: 'QC2_WIND',
            NavigationName: 'Gió',
            NavigationNameEN: 'WIND',
            Order: 2,
            Status: 1,
          },
          {
            ParentNavigationId: 531,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/pressure',
            IconClass: 'fa fa-compress',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 535,
            NavigationCode: 'QC2_PRESSURE',
            NavigationName: 'Khí áp',
            NavigationNameEN: 'PRESSURE',
            Order: 3,
            Status: 1,
          },
          {
            ParentNavigationId: 531,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/visibility',
            IconClass: 'fa fa-eye',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 536,
            NavigationCode: 'QC2_VISIBILITY',
            NavigationName: 'Tầm nhìn ngang',
            NavigationNameEN: 'HORIZONTAL_VISIBILITY',
            Order: 4,
            Status: 1,
          },
        ],
      },
      {
        ParentNavigationId: 530,
        ApplicationId: 1,
        HasChild: true,
        UrlRewrite: '',
        IconClass: 'fa fa-tint',
        IsSystem: true,
        RoleId: 0,
        NavigationId: 541,
        NavigationCode: 'QC2_HYDRO',
        NavigationName: 'Thủy văn',
        NavigationNameEN: 'HYDROLOGY',
        Order: 1,
        Status: 1,
        RightCodes: [],
        SubNavigation: [
          {
            ParentNavigationId: 541,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/rain',
            IconClass: 'fa fa-umbrella',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 542,
            NavigationCode: 'QC2_RAIN',
            NavigationName: 'Mưa',
            NavigationNameEN: 'RAIN',
            Order: 0,
            Status: 1,
          },
          {
            ParentNavigationId: 541,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/waterlevel',
            IconClass: 'fa fa-bars',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 543,
            NavigationCode: 'QC2_WATER_LEVEL',
            NavigationName: 'Mực nước',
            NavigationNameEN: 'WATER_LEVEL',
            Order: 1,
            Status: 1,
          },
          {
            ParentNavigationId: 541,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/discharge',
            IconClass: 'fa fa-exchange',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 544,
            NavigationCode: 'QC2_DISCHARGE',
            NavigationName: 'Lưu lượng nước',
            NavigationNameEN: 'DISCHARGE',
            Order: 2,
            Status: 1,
          },
          {
            ParentNavigationId: 541,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/qc2/independent-rain',
            IconClass: 'fa fa-tint',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 545,
            NavigationCode: 'QC2_RAIN_INDEPENDENT',
            NavigationName: 'Mưa độc lập',
            NavigationNameEN: 'INDEPENDENT_RAIN',
            Order: 3,
            Status: 1,
          },
        ],
      },
    ],
  },

  /* ================= HQC ================= */
  {
    ApplicationId: 1,
    HasChild: true,
    IconClass: 'fa fa-sliders',
    IsSystem: true,
    RoleId: 0,
    NavigationId: 560,
    NavigationCode: 'QUALITY_HQC',
    NavigationName: 'Thiết lập theo HQC',
    NavigationNameEN: 'QUALITY_HQC',
    Order: 2,
    Status: 1,
    CreatedOnDate: '2025-10-04T00:00:00',
    LastModifiedOnDate: '2025-10-04T00:00:00',
    RightCodes: [],
    SubNavigation: [
      {
        ParentNavigationId: 560,
        ApplicationId: 1,
        HasChild: true,
        UrlRewrite: '',
        IconClass: 'fa fa-tint',
        IsSystem: true,
        RoleId: 0,
        NavigationId: 561,
        NavigationCode: 'HQC_HYDRO',
        NavigationName: 'Thủy văn',
        NavigationNameEN: 'HYDROLOGY',
        Order: 0,
        Status: 1,
        RightCodes: [],
        SubNavigation: [
          {
            ParentNavigationId: 561,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/hqc/independent-rain',
            IconClass: 'fa fa-tint',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 562,
            NavigationCode: 'HQC_RAIN_INDEPENDENT',
            NavigationName: 'Mưa độc lập',
            NavigationNameEN: 'INDEPENDENT_RAIN',
            Order: 0,
            Status: 1,
          },
          {
            ParentNavigationId: 561,
            ApplicationId: 1,
            HasChild: false,
            UrlRewrite: '/hqc/rainfall',
            IconClass: 'fa fa-umbrella',
            IsSystem: true,
            RoleId: 0,
            SubNavigation: [],
            RightCodes: [
              'VIEW',
              'CREATE',
              'UPDATE',
              'DELETE',
              'SEARCH',
              'IMPORT',
              'EXPORT',
            ],
            NavigationId: 563,
            NavigationCode: 'HQC_RAINFALL',
            NavigationName: 'Lượng mưa',
            NavigationNameEN: 'RAINFALL',
            Order: 1,
            Status: 1,
          },
        ],
      },
    ],
  },

  /* ======== Kết quả & Báo cáo ======== */
  {
    ApplicationId: 1,
    HasChild: false,
    UrlRewrite: '/quality/results',
    IconClass: 'fa fa-list-alt',
    IsSystem: true,
    RoleId: 0,
    SubNavigation: [],
    RightCodes: ['VIEW', 'SEARCH', 'EXPORT'],
    NavigationId: 580,
    NavigationCode: 'QUALITY_RESULTS',
    NavigationName: 'Kết quả kiểm tra',
    NavigationNameEN: 'QUALITY_RESULTS',
    Order: 3,
    Status: 1,
    CreatedOnDate: '2025-10-04T00:00:00',
  },
  {
    ApplicationId: 1,
    HasChild: false,
    UrlRewrite: '/quality/reports',
    IconClass: 'fa fa-bar-chart',
    IsSystem: true,
    RoleId: 0,
    SubNavigation: [],
    RightCodes: ['VIEW', 'SEARCH', 'EXPORT'],
    NavigationId: 581,
    NavigationCode: 'QUALITY_REPORT',
    NavigationName: 'Báo cáo thống kê',
    NavigationNameEN: 'QUALITY_REPORT',
    Order: 4,
    Status: 1,
    CreatedOnDate: '2025-10-04T00:00:00',
  },
];
