/*******************************************************************************
 * Project：
 * Summary:
 *　　 IconComponent
 * Remarks:
 *     inspec common component
 * History：
 *      AnBD            2021/07/26    Create
 ******************************************************************************/
import { Component, EventEmitter, Input, OnInit, Output, SimpleChanges, ElementRef, ChangeDetectionStrategy } from '@angular/core';
import { Utility } from '~/app/utils/utility';
import * as _ from 'lodash';
import { TranslateService } from '@ngx-translate/core';
@Component({
  selector: 'app-inp-icon',
  templateUrl: './icon.component.html',
  styleUrls: ['./icon.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush

})
export class IconComponent implements OnInit {
  @Input() item: string;
  @Input() class: string;
  @Input() isDisabled: boolean;
  @Input() itemCode: any;
  @Output() eventSelectValue = new EventEmitter();
  @Input() placeholder: string = 'LINK_ICON';
  lstChange: any;
  showDropDown = false;
  disableBtn = false;
  code: any;
  type: any;
  itemText: string;
  sltWithKey: any = [];
  lstItem: any;
  OldlstItem: any;
  classIcon: string;
  constructor(private util: Utility, private el: ElementRef,
    public translate: TranslateService) {
    this.SetData();
    this.OldlstItem = JSON.stringify(this.lstItem);
  }
  ngOnChanges(changes: SimpleChanges): void {
    if (!this.util.isNullOrBlank(changes) && !this.util.isNullOrBlank(changes.itemCode)) {
      this.classIcon = changes.itemCode.currentValue?.trim();
    }
  }
  SetData() {
    this.lstItem = [
      {  code: ' '},
      {  code: 'fa fa-mail-forward' },
      {  code: 'fa fa-barcode' },
      {  code: 'fa fa-tag  ' },
      {  code: 'fa fa-tags  ' },
      {  code: 'fa fa-book  ' },
      {  code: 'fa fa-bookmark  ' },
      {  code: 'fa fa-print  ' },
      {  code: 'fa fa-camera  ' },
      {  code: 'fa fa-font  ' },
      {  code: 'fa fa-bold  ' },
      {  code: 'fa fa-italic  ' },
      {  code: 'fa fa-text-height ' },
      {  code: 'fa fa-text-width ' },
      {  code: 'fa fa-align-left ' },
      {  code: 'fa fa-align-center ' },
      {  code: 'fa fa-align-right ' },
      {  code: 'fa fa-align-justify ' },
      {  code: 'fa fa-list  ' },
      {  code: 'fa fa-dedent  ' },
      {  code: 'fa fa-outdent  ' },
      {  code: 'fa fa-indent  ' },
      {  code: 'fa fa-video-camera ' },
      {  code: 'fa fa-image   ' },
      {  code: 'fa fa-backward  ' },
      {  code: 'fa fa-play  ' },
      {  code: 'fa fa-pause  ' },
      {  code: 'fa fa-stop  ' },
      {  code: 'fa fa-exclamation-triangle  ' },
      {  code: 'fa fa-plane  ' },
      {  code: 'fa fa-calendar  ' },
      {  code: 'fa fa-random  ' },
      {  code: 'fa fa-comment  ' },
      {  code: 'fa fa-magnet  ' },
      {  code: 'fa fa-chevron-up ' },
      {  code: 'fa fa-chevron-down ' },
      {  code: 'fa fa-retweet  ' },
      {  code: 'fa fa-shopping-cart ' },
      {  code: 'fa fa-folder  ' },
      {  code: 'fa fa-folder-open  ' },
      {  code: 'fa fa-arrows-v ' },
      {  code: 'fa fa-arrows-h ' },
      {  code: 'fa fa-bar-chart-o ' },
      {  code: 'fa fa-bar-chart ' },
      {  code: 'fa fa-twitter-square ' },
      {  code: 'fa fa-facebook-square  ' },
      {  code: 'fa fa-camera-retro  ' },
      {  code: 'fa fa-key  ' },
      {  code: 'fa fa-gears  ' },
      {  code: 'fa fa-cogs  ' },
      {  code: 'fa fa-comments  ' },
      {  code: 'fa fa-qrthumbs-o-upcode ' },
      {  code: 'fa fa-thumbs-o-down ' },
      {  code: 'fa fa-star-half ' },
      {  code: 'fa fa-heart-o ' },
      {  code: 'fa fa-sign-out ' },
      {  code: 'fa fa-linkedin-square ' },
      {  code: 'fa fa-thumb-tack ' },
      {  code: 'fa fa-external-link  ' },
      {  code: 'fa fa-sign-in ' },
      {  code: 'fa fa-trophy  ' },
      {  code: 'fa fa-github-square  ' },
      {  code: 'fa fa-upload  ' },
      {  code: 'fa fa-qrcode ' },
      {  code: 'fa fa-lemon-o  ' },
      {  code: 'fa fa-phone  ' },
      {  code: 'fa fa-square-o ' },
      {  code: 'fa fa-bookmark-o ' },
      {  code: 'fa fa-phone-square ' },
      {  code: 'fa fa-twitter ' },
      {  code: 'fa fa-facebook-f ' },
      {  code: 'fa fa-facebook  ' },
      {  code: 'fa fa-github  ' },
      {  code: 'fa fa-unlock  ' },
      {  code: 'fa fa-credit-card ' },
      {  code: 'fa fa-feed' },
      {  code: 'fa fa-rss  ' },
      {  code: 'fa fa-hdd-o ' },
      {  code: 'fa fa-bullhorn ' },
      {  code: 'fa fa-bell ' },
      {  code: 'fa fa-certificate ' },
      {  code: 'fa fa-hand-o-right ' },
      {  code: 'fa fa-hand-o-left ' },
      {  code: 'fa fa-hand-o-up ' },
      {  code: 'fa fa-hand-o-down ' },
      {  code: 'fa fa-arrow-circle-left ' },
      {  code: 'fa fa-arrow-circle-right ' },
      {  code: 'fa fa-arrow-circle-up ' },
      {  code: 'fa fa-arrow-circle-down ' },
      {  code: 'fa fa-wrench' },
      {  code: 'fa fa-tasks' },
      {  code: 'fa fa-filter' },
      {  code: 'fa fa-briefcase ' },
      {  code: 'fa fa-arrows-alt ' },
      {  code: 'fa fa-users  ' },
      {  code: 'fa fa-chain ' },
      {  code: 'fa fa-link ' },
      {  code: 'fa fa-cloud ' },
      {  code: 'fa fa-flask ' },
      {  code: 'fa fa-cut' },
      {  code: 'fa fa-scissors' },
      {  code: 'fa fa-paperclip' },
      {  code: 'fa fa-files-o' },
      {  code: 'fa fa-save ' },
      {  code: 'fa fa-floppy-o ' },
      {  code: 'fa fa-navicon   ' },
      {  code: 'fa fa-reorder  ' },
      {  code: 'fa fa-bars  ' },
      {  code: 'fa fa-list-ul ' },
      {  code: 'fa fa-list-ol ' },
      {  code: 'fa fa-strikethrough  ' },
      {  code: 'fa fa-underline  ' },
      {  code: 'fa fa-table  ' },
      {  code: 'fa fa-magic  ' },
      {  code: 'fa fa-truck  ' },
      {  code: 'fa fa-pinterest  ' },
      {  code: 'fa fa-pinterest-square ' },
      {  code: 'fa fa-google-plus-square ' },
      {  code: 'fa fa-google-plus ' },
      {  code: 'fa fa-money  ' },
      {  code: 'fa fa-caret-down ' },
      {  code: 'fa fa-caret-up ' },
      {  code: 'fa fa-caret-left ' },
      {  code: 'fa fa-caret-right ' },
      {  code: 'fa fa-columns ' },
      {  code: 'fa fa-unsorted ' },
      {  code: 'fa fa-sort ' },
      {  code: 'fa fa-down ' },
      {  code: 'fa fa-sort-desc  ' },
      {  code: 'fa fa-sort-up' },
      {  code: 'fa fa-sort-asc ' },
      {  code: 'fa fa-envelope ' },
      {  code: 'fa fa-linkedin  ' },
      {  code: 'fa fa-rotate-left ' },
      {  code: 'fa fa-undo  ' },
      {  code: 'fa fa-legal  ' },
      {  code: 'fa fa-gavel  ' },
      {  code: 'fa fa-dashboard  ' },
      {  code: 'fa fa-tachometer  ' },
      {  code: 'fa fa-comment-o ' },
      {  code: 'fa fa-flash  ' },
      {  code: 'fa fa-bolt  ' },
      {  code: 'fa fa-sitemap  ' },
      {  code: 'fa fa-umbrella  ' },
      {  code: 'fa fa-paste  ' },
      {  code: 'fa fa-clipboard  ' },
      {  code: 'fa fa-lightbulb-o ' },
      {  code: 'fa fa-exchange  ' },
      {  code: 'fa fa-cloud-download ' },
      {  code: 'fa fa-cloud-upload  ' },
      {  code: 'fa fa-user-md ' },
      {  code: 'fa fa-eraser ' },
      {  code: 'fa fa-puzzle-piece' },
      {  code: 'fa fa-microphone ' },
      {  code: 'fa fa-microphone-slash' },
      {  code: 'fa fa-shield ' },
      {  code: 'fa fa-calendar-o' },
      {  code: 'fa fa-fire-extinguisher' },
      {  code: 'fa fa-rocket ' },
      {  code: 'fa fa-maxcdn ' },
      {  code: 'fa fa-chevron-circle-left' },
      {  code: 'fa fa-chevron-circle-right' },
      {  code: 'fa fa-chevron-circle-up ' },
      {  code: 'fa fa-chevron-circle-down' },
      {  code: 'fa fa-html5 ' },
      {  code: 'fa fa-css3 ' },
      {  code: 'fa fa-anchor ' },
      {  code: 'fa fa-unlock-alt' },
      {  code: 'fa fa-bullseye ' },
      {  code: 'fa fa-ellipsis-h' },
      {  code: 'fa fa-ellipsis-v ' },
      {  code: 'fa fa-rss-square' },
      {  code: 'fa fa-play-circle ' },
      {  code: 'fa fa-ticket ' },
      {  code: 'fa fa-minus-square ' },
      {  code: 'fa fa-minus-square-o' },
      {  code: 'fa fa-level-up' },
      {  code: 'fa fa-level-down' },
      {  code: 'fa fa-check-square' },
      {  code: 'fa fa-pencil-square' },
      {  code: 'fa fa-external-link-square' },
      {  code: 'fa fa-share-square' },
      {  code: 'fa fa-compass ' },
      {  code: 'fa fa-toggle-down' },
      {  code: 'fa fa-caret-square-o-down' },
      {  code: 'fa fa-toggle-up' },
      {  code: 'fa fa-caret-square-o-up' },
      {  code: 'fa fa-toggle-right' },
      {  code: 'fa fa-caret-square-o-right' },
      {  code: 'fa fa-euro  ' },
      {  code: 'fa fa-eur  ' },
      {  code: 'fa fa-gbp  ' },
      {  code: 'fa fa-usd   ' },
      {  code: 'fa fa-rupee  ' },
      {  code: 'fa fa-inr ' },
      {  code: 'fa fa-cny ' },
      {  code: 'fa fa-rmb ' },
      {  code: 'fa fa-yen  ' },
      {  code: 'fa fa-jpy  ' },
      {  code: 'fa fa-ruble  ' },
      {  code: 'fa fa-rouble  ' },
      {  code: 'fa fa-rub  ' },
      {  code: 'fa fa-won  ' },
      {  code: 'fa fa-krw  ' },
      {  code: 'fa fa-bitcoin  ' },
      {  code: 'fa fa-btc  ' },
      {  code: 'fa fa-file  ' },
      {  code: 'fa fa-file-text ' },
      {  code: 'fa fa-sort-alpha-asc ' },
      {  code: 'fa fa-sort-alpha-desc  ' },
      {  code: 'fa fa-sort-amount-asc ' },
      {  code: 'fa fa-sort-amount-desc ' },
      {  code: 'fa fa-sort-numeric-asc ' },
      {  code: 'fa fa-sort-numeric-desc  ' },
      {  code: 'fa fa-thumbs-up ' },
      {  code: 'fa fa-thumbs-down ' },
      {  code: 'fa fa-youtube-square ' },
      {  code: 'fa fa-youtube  ' },
      {  code: 'fa fa-xing  ' },
      {  code: 'fa fa-xing-square ' },
      {  code: 'fa fa-youtube-play  ' },
      {  code: 'fa fa-stack-overflow   ' },
      {  code: 'fa fa-instagram  ' },
      {  code: 'fa fa-flickr  ' },
      {  code: 'fa fa-adn  ' },
      {  code: 'fa fa-bitbucket  ' },
      {  code: 'fa fa-bitbucket-square  ' },
      {  code: 'fa fa-tumblr  ' },
      {  code: 'fa fa-tumblr-square ' },
      {  code: 'fa fa-long-arrow-down ' },
      {  code: 'fa fa-long-arrow-up ' },
      {  code: 'fa fa-long-arrow-left ' },
      {  code: 'fa fa-long-arrow-right ' },
      {  code: 'fa fa-apple  ' },
      {  code: 'fa fa-linux  ' },
      {  code: 'fa fa-dribbble  ' },
      {  code: 'fa fa-skype  ' },
      {  code: 'fa fa-foursquare  ' },
      {  code: 'fa fa-trello  ' },
      {  code: 'fa fa-female  ' },
      {  code: 'fa fa-male  ' },
      {  code: 'fa fa-gittip  ' },
      {  code: 'fa fa-gratipay  ' },
      {  code: 'fa fa-sun-o ' },
      {  code: 'fa fa-moon-o ' },
      {  code: 'fa fa-bug   ' },
      {  code: 'fa fa-vk  ' },
      {  code: 'fa fa-weibo  ' },
      {  code: 'fa fa-renren  ' },
      {  code: 'fa fa-pagelines  ' },
      {  code: 'fa fa-stack-exchange  ' },
      {  code: 'fa fa-arrow-circle-o-right ' },
      {  code: 'fa fa-arrow-circle-o-left ' },
      {  code: 'fa fa-toggle-left ' },
      {  code: 'fa fa-caret-square-o-left ' },
      {  code: 'fa fa-dot-circle-o ' },
      {  code: 'fa fa-wheelchair  ' },
      {  code: 'fa fa-vimeo-square ' },
      {  code: 'fa fa-turkish-lira  ' },
      {  code: 'fa fa-try  ' },
      {  code: 'fa fa-plus-square-o ' },
      {  code: 'fa fa-space-shuttle ' },
      {  code: 'fa fa-slack  ' },
      {  code: 'fa fa-envelope-square ' },
      {  code: 'fa fa-wordpress  ' },
      {  code: 'fa fa-openid  ' },
      {  code: 'fa fa-stethoscope  ' },
      {  code: 'fa fa-suitcase  ' },
      {  code: 'fa fa-bell-o ' },
      {  code: 'fa fa-coffee  ' },
      {  code: 'fa fa-cutlery  ' },
      {  code: 'fa fa-file-text-o ' },
      {  code: 'fa fa-building-o  ' },
      {  code: 'fa fa-hospital-o  ' },
      {  code: 'fa fa-ambulance  ' },
      {  code: 'fa fa-medkit  ' },
      {  code: 'fa fa-fighter-jet ' },
      {  code: 'fa fa-beer  ' },
      {  code: 'fa fa-h-square ' },
      {  code: 'fa fa-plus-square  ' },
      {  code: 'fa fa-angle-double-left ' },
      {  code: 'fa fa-ngle-double-right  ' },
      {  code: 'fa fa-angle-double-up ' },
      {  code: 'fa fa-bolt ' },
      {  code: 'fa fa-sitemap ' },
      {  code: 'fa fa-umbrella ' },
      {  code: 'fa fa-paste ' },
      {  code: 'fa fa-clipboard ' },
      {  code: 'fa fa-ightbulb-o ' },
      {  code: 'fa fa-exchange ' },
      {  code: 'fa fa-cloud-download ' },
      {  code: 'fa fa-cloud-upload ' },
      {  code: 'fa fa-desktop' },
      {  code: 'fa fa-laptop ' },
      {  code: 'fa fa-tablet ' },
      {  code: 'fa fa-mobile-phone' },
      {  code: 'fa fa-mobile ' },
      {  code: 'fa fa-circle-o' },
      {  code: 'fa fa-quote-left' },
      {  code: 'fa fa-quote-right ' },
      {  code: 'fa fa-circle ' },
      {  code: 'fa fa-mail-reply' },
      {  code: 'fa fa-github-alt ' },
      {  code: 'fa fa-folder-o ' },
      {  code: 'fa fa-folder-open-o' },
      {  code: 'fa fa-smile-o ' },
      {  code: 'fa fa-frown-o' },
      {  code: 'fa fa-meh-o' },
      {  code: 'fa fa-gamepad ' },
      {  code: 'fa fa-keyboard-o  ' },
      {  code: 'fa fa-flag-o' },
      {  code: 'fa fa-flag-checkered ' },
      {  code: 'fa fa-terminal ' },
      {  code: 'fa fa-mail-reply-all  ' },
      {  code: 'fa fa-reply-all ' },
      {  code: 'fa fa-star-half-empty' },
      {  code: 'fa fa-star-half-full' },
      {  code: 'fa fa-star-half-o' },
      {  code: 'fa fa-location-arrow' },
      {  code: 'fa fa-crop  ' },
      {  code: 'fa fa-code-fork' },
      {  code: 'fa fa-unlink ' },
      {  code: 'fa fa-chain-broken' },
      {  code: 'fa fa-question  ' },
      {  code: 'fa fa-info ' },
      {  code: 'fa fa-exclamation ' },
      {  code: 'fa fa-superscript ' },
      {  code: 'fa fa-share' },
      {  code: 'fa fa-expand' },
      {  code: 'fa fa-compress' },
      {  code: 'fa fa-plus' },
      {  code: 'fa fa-asterisk' },
      {  code: 'fa fa-exclamation' },
      {  code: 'fa fa-gift' },
      {  code: 'fa fa-leaf' },
      {  code: 'fa fa-fire' },
      {  code: 'fa fa-rotate-right' },
      {  code: 'fa fa-repeat' },
      {  code: 'fa fa-refresh' },
      {  code: 'fa fa-list-alt' },
      {  code: 'fa fa-flag' },
      {  code: 'fa fa-headphones' },
      {  code: 'fa fa-volume-down' },
      {  code: 'fa fa-volume-up' },
      {  code: 'fa fa-qrcode ' },
      {  code: 'fa fa-music' },
      {  code: 'fa fa-glass' },
      {  code: 'fa fa-search' },
      {  code: 'fa fa-envelope-o' },
      {  code: 'fa fa-heart' },
      {  code: 'fa fa-star' },
      {  code: 'fa fa-star-o' },
      {  code: 'fa fa-exclamation' },
      {  code: 'fa fa-exclamation-circle' },
      {  code: 'fa fa-blind' },
      {  code: 'fa fa-braille' },
      {  code: 'fa fa-deaf' },
      {  code: 'fa fa-low-vision' },
      {  code: 'fa fa-question-circle' },
      {  code: 'fa fa-sign-language' },
      {  code: 'fa fa-tty' },
      {  code: 'fa fa-universal-access' },
      {  code: 'fa fa-wheelchair' },
      {  code: 'fa fa-angle-double-down' },
      {  code: 'fa fa-angle-double-left' },
      {  code: 'fa fa-angle-double-right' },
      {  code: 'fa fa-angle-double-up' },
      {  code: 'fa fa-angle-down' },
      {  code: 'fa fa-angle-left' },
      {  code: 'fa fa-archive' },
      {  code: 'fa fa-book' },
      {  code: 'fa fa-bookmark' },
      {  code: 'fa fa-bookmark' },
      {  code: 'fa fa-edit' },
      {  code: 'fa fa-envelope-open' },
      {  code: 'fa fa-eraser' },
      {  code: 'fa fa-file' },
      {  code: 'fa fa-folder' },
      {  code: 'fa fa-folder-open' },
      {  code: 'fa fa-paper-plane' },
      {  code: 'fa fa-bolt' },
      {  code: 'fa fa-car' },
      {  code: 'fa fa-bicycle' },
      {  code: 'fa fa-fighter-jet' },
      {  code: 'fa fa-paper-plane' },
      {  code: 'fa fa-wheelchair' },
      {  code: 'fa fa-address-book' },
      {  code: 'fa fa-address-card' },
      {  code: 'fa fa-id-badge' },
      {  code: 'fa fa-male' },
      {  code: 'fa fa-power-off' },
      {  code: 'fa fa-user-circle' },
      {  code: 'fa fa-user-plus' },
      {  code: 'fa fa-user' },
      {  code: 'fa fa-microphone' },
      {  code: 'fa fa-microphone-slash' },
      {  code: 'fa fa-star' },
      {  code: 'fa fa-wifi' },
      {  code: 'fa fa-toggle-on' },
      {  code: 'fa fa-toggle-off' },
      {  code: 'fa fa-ban' },
      {  code: 'fa fa-battery-empty' },
      {  code: 'fa fa-battery-full' },
      {  code: 'fa fa-bell' },
      {  code: 'fa fa-bell-slash' },
      {  code: 'fa fa-calendar' },
      {  code: 'fa fa-cart-plus' },
      {  code: 'fa fa-comment' },
      {  code: 'fa fa-eye' },
      {  code: 'fa fa-eye-slash' },
      {  code: 'fa fa-file' },
      {  code: 'fa fa-folder' },
      {  code: 'fa fa-folder-open' },
      {  code: 'fa fa-info' },
      {  code: 'fa fa-lock' },
      {  code: 'fa fa-phone' },
      {  code: 'fa fa-plus' },
      {  code: 'fa fa-volume-down' },
      {  code: 'fa fa-volume-off' },
      {  code: 'fa fa-volume-up' },
      {  code: 'fa fa-heart' },
      {  code: 'fa fa-image' },
      {  code: 'fa fa-share-square' },
      {  code: 'fa fa-thumbs-up' },
      {  code: 'fa fa-history' },
      {  code: 'fa fa-bullhorn' },
      {  code: 'fa fa-handshake' },
      {  code: 'fa fa-tags' },
      {  code: 'fa fa-thumbs-down' },
      {  code: 'fa fa-thumbs-up' },
      {  code: 'fa fa-compass' },
      {  code: 'fa fa-cube' },
      {  code: 'fa fa-cut' },
      {  code: 'fa fa-feather' },
      {  code: 'fa fa-gift' },
      {  code: 'fa fa-gavel' },
      {  code: 'fa fa-home' },
      {  code: 'fa fa-wrench' },
      {  code: 'fa fa-music' },
      {  code: 'fa fa-recycle' },
      {  code: 'fa fa-plus-square' },
      {  code: 'fa fa-search-plus' },
      {  code: 'fa fa-search-minus' },
      {  code: 'fa fa-search' },
      {  code: 'fa fa-film' },
      {  code: 'fa fa-th-large' },
      {  code: 'fa fa-th' },
      {  code: 'fa fa-th-list' },
      {  code: 'fa fa-check' },
      {  code: 'fa fa-remove' },
      {  code: 'fa fa-close' },
      {  code: 'fa fa-times' },
      {  code: 'fa fa-signal' },
      {  code: 'fa fa-gear' },
      {  code: 'fa fa-cog' },
      {  code: 'fa fa-trash-o' },
      {  code: 'fa fa-clock-o' },
      {  code: 'fa fa-file-o' },
      {  code: 'fa fa-clock-o' },
      {  code: 'fa fa-road' },
      {  code: 'fa fa-download' },
      {  code: 'fa fa-arrow-circle-o-down' },
      {  code: 'fa fa-arrow-circle-o-up' },
      {  code: 'fa fa-play-circle-o' },
      {  code: 'fa fa-picture-o' },
      {  code: 'fa fa-pencil' },
      {  code: 'fa fa-adjust' },
      {  code: 'fa fa-tint' },
      {  code: 'fa fa-pencil-square-o' },
      {  code: 'fa fa-check-square-o' },
      {  code: 'fa fa-arrows' },
      {  code: 'fa fa-step-backward' },
      {  code: 'fa fa-fast-backward' },
      {  code: 'fa fa-play' },
      {  code: 'fa fa-pause' },
      {  code: 'fa fa-stop' },
      {  code: 'fa fa-forward' },
      {  code: 'fa fa-fast-forward' },
      {  code: 'fa fa-step-forward' },
      {  code: 'fa fa-eject' },
      {  code: 'fa fa-chevron-left' },
      {  code: 'fa fa-chevron-right' },
      {  code: 'fa fa-plus-circle' },
      {  code: 'fa fa-minus-circle' },
      {  code: 'fa fa-times-circle' },
      {  code: 'fa fa-check-circle' },
      {  code: 'fa fa-question-circle' },
      {  code: 'fa fa-info-circle' },
      {  code: 'fa fa-crosshairs' },
      {  code: 'fa fa-times-circle-o' },
      {  code: 'fa fa-check-circle-o' },
      {  code: 'fa fa-ban' },
      {  code: 'fa fa-arrow-left' },
      {  code: 'fa fa-arrow-right' },
      {  code: 'fa fa-arrow-up' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-institution ' },
      {  code: 'fa fa-bank ' },
      {  code: 'fa fa-university ' },
      {  code: 'fa fa-mortar-' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-graduation-cap' },
      {  code: 'fa fa-yahoo ' },
      {  code: 'fa fa-google ' },
      {  code: 'fa fa-reddit ' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-reddit-square' },
      {  code: 'fa fa-stumbleupon-circle' },
      {  code: 'fa fa-stumbleupon ' },
      {  code: 'fa fa-crosshairs' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-delicious ' },
      {  code: 'fa fa-digg' },
      {  code: 'fa fa-pied-piper-pp' },
      {  code: 'fa fa-pied-piper-alt' },
      {  code: 'fa fa-drupal' },
      {  code: 'fa fa-joomla ' },
      {  code: 'fa fa-language ' },
      {  code: 'fa fa-fax ' },
      {  code: 'fa fa-building ' },
      {  code: 'fa fa-child ' },
      {  code: 'fa fa-paw ' },
      {  code: 'fa fa-spoon ' },
      {  code: 'fa fa-cube ' },
      {  code: 'fa fa-cubes ' },
      {  code: 'fa fa-behance ' },
      {  code: 'fa fa-behance-square' },
      {  code: 'fa fa-steam ' },
      {  code: 'fa fa-steam-square' },
      {  code: 'fa fa-recycle ' },
      {  code: 'fa fa-automobile ' },
      {  code: 'fa fa-car ' },
      {  code: 'fa fa-cab ' },
      {  code: 'fa fa-taxi ' },
      {  code: 'fa fa-tree ' },
      {  code: 'fa fa-spotify ' },
      {  code: 'fa fa-soundcloud ' },
      {  code: 'fa fa-database ' },
      {  code: 'fa fa-file-pdf-o' },
      {  code: 'fa fa-file-word-o' },
      {  code: 'fa fa-file-powerpoint-o' },
      {  code: 'fa fa-file-photo-o' },
      {  code: 'fa fa-file-picture-o' },
      {  code: 'fa fa-file-image-o' },
      {  code: 'fa fa-file-zip-o' },
      {  code: 'fa fa-file-archive-o' },
      {  code: 'fa fa-file-sound-o' },
      {  code: 'fa fa-file-audio-o ' },
      {  code: 'fa fa-file-movie-o' },
      {  code: 'fa fa-file-video-o' },
      {  code: 'fa fa-file-code-o' },
      {  code: 'fa fa-vine' },
      {  code: 'fa fa-codepen ' },
      {  code: 'fa fa-jsfiddle ' },
      {  code: 'fa fa-life-bouy' },
      {  code: 'fa fa-life-buoy' },
      {  code: 'fa fa-life-saver' },
      {  code: 'fa fa-support ' },
      {  code: 'fa fa-life-ring' },
      {  code: 'fa fa-circle-o-notch' },
      {  code: 'fa fa-ra' },
      {  code: 'fa fa-resistance ' },
      {  code: 'fa fa-rebel ' },
      {  code: 'fa fa-ge ' },
      {  code: 'fa fa-empire ' },
      {  code: 'fa fa-git-square' },
      {  code: 'fa fa-git ' },
      {  code: 'fa fa-y-combinator-square' },
      {  code: 'fa fa-yc-square' },
      {  code: 'fa fa-hacker-news' },
      {  code: 'fa fa-tencent-weibo' },
      {  code: 'fa fa-qq' },
      {  code: 'fa fa-wechat ' },
      {  code: 'fa fa-weixin ' },
      {  code: 'fa fa-send ' },
      {  code: 'fa fa-paper-plane' },
      {  code: 'fa fa-send-o' },
      {  code: 'fa fa-paper-plane-o' },
      {  code: 'fa fa-history ' },
      {  code: 'fa fa-circle-thin' },
      {  code: 'fa fa-header ' },
      {  code: 'fa fa-paragraph ' },
      {  code: 'fa fa-sliders ' },
      {  code: 'fa fa-share-alt' },
      {  code: 'fa fa-share-alt-square' },
      {  code: 'fa fa-bomb ' },
      {  code: 'fa fa-soccer-ball-o' },
      {  code: 'fa fa-futbol-o' },
      {  code: 'fa fa-tty ' },
      {  code: 'fa fa-plug  ' },
      {  code: 'fa fa-slideshare ' },
      {  code: 'fa fa-twitch ' },
      {  code: 'fa fa-yelp ' },
      {  code: 'fa fa-newspaper-o' },
      {  code: 'fa fa-wifi ' },
      {  code: 'fa fa-calculator ' },
      {  code: 'fa fa-paypal ' },
      {  code: 'fa fa-google-wallet' },
      {  code: 'fa fa-cc-visa' },
      {  code: 'fa fa-cc-mastercard' },
      {  code: 'fa fa-cc-discover' },
      {  code: 'fa fa-cc-amex' },
      {  code: 'fa fa-cc-paypal' },
      {  code: 'fa fa-cc-stripe' },
      {  code: 'fa fa-bell-slash' },
      {  code: 'fa fa-bell-slash-o' },
      {  code: 'fa fa-trash ' },
      {  code: 'fa fa-at  ' },
      {  code: 'fa fa-eyedropper ' },
      {  code: 'fa fa-crosshairs' },
      {  code: 'fa fa-paint-brush' },
      {  code: 'fa fa-birthday-cake' },
      {  code: 'fa fa-area-chart' },
      {  code: 'fa fa-pie-chart' },
      {  code: 'fa fa-line-chart' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-lastfm ' },
      {  code: 'fa fa-lastfm-square ' },
      {  code: 'fa fa-toggle-off' },
      {  code: 'fa fa-toggle-on' },
      {  code: 'fa fa-bicycle ' },
      {  code: 'fa fa-bus ' },
      {  code: 'fa fa-ioxhost ' },
      {  code: 'fa fa-angellist ' },
      {  code: 'fa fa-cc ' },
      {  code: 'fa fa-shekel ' },
      {  code: 'fa fa-sheqel ' },
      {  code: 'fa fa-ils ' },
      {  code: 'fa fa-meanpath ' },
      {  code: 'fa fa-buysellads ' },
      {  code: 'fa fa-connectdevelop ' },
      {  code: 'fa fa-dashcube ' },
      {  code: 'fa fa-forumbee ' },
      {  code: 'fa fa-leanpub ' },
      {  code: 'fa fa-sellsy ' },
      {  code: 'fa fa-shirtsinbulk ' },
      {  code: 'fa fa-simplybuilt ' },
      {  code: 'fa fa-skyatlas ' },
      {  code: 'fa fa-cart-plus' },
      {  code: 'fa fa-cart-arrow-down ' },
      {  code: 'fa fa-diamond ' },
      {  code: 'fa fa-ship ' },
      {  code: 'fa fa-user-secret' },
      {  code: 'fa fa-motorcycle ' },
      {  code: 'fa fa-street-view' },
      {  code: 'fa fa-heartbeat ' },
      {  code: 'fa fa-venus ' },
      {  code: 'fa fa-mars ' },
      {  code: 'fa fa-mercury ' },
      {  code: 'fa fa-intersex ' },
      {  code: 'fa fa-transgender ' },
      {  code: 'fa fa-transgender-alt' },
      {  code: 'fa fa-venus-double' },
      {  code: 'fa fa-mars-double' },
      {  code: 'fa fa-venus-mars' },
      {  code: 'fa fa-mars-stroke' },
      {  code: 'fa fa-mars-stroke-v' },
      {  code: 'fa fa-mars-stroke-h' },
      {  code: 'fa fa-neuter ' },
      {  code: 'fa fa-genderless ' },
      {  code: 'fa fa-facebook-official' },
      {  code: 'fa fa-pinterest-p' },
      {  code: 'fa fa-whatsapp ' },
      {  code: 'fa fa-server ' },
      {  code: 'fa fa-user-plus' },
      {  code: 'fa fa-optin-monster' },
      {  code: 'fa fa-user-times' },
      {  code: 'fa fa-hotel ' },
      {  code: 'fa fa-bed ' },
      {  code: 'fa fa-y-combinator' },
      {  code: 'fa fa-viacoin ' },
      {  code: 'fa fa-train ' },
      {  code: 'fa fa-subway ' },
      {  code: 'fa fa-medium ' },
      {  code: 'fa fa-yc ' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-opencart ' },
      {  code: 'fa fa-expeditedssl ' },
      {  code: 'fa fa-battery-4' },
      {  code: 'fa fa-battery ' },
      {  code: 'fa fa-battery-full' },
      {  code: 'fa fa-battery-3' },
      {  code: 'fa fa-battery-three-quarters' },
      {  code: 'fa fa-battery-2' },
      {  code: 'fa fa-battery-half' },
      {  code: 'fa fa-battery-1' },
      {  code: 'fa fa-battery-quarter' },
      {  code: 'fa fa-battery-0' },
      {  code: 'fa fa-battery-empty' },
      {  code: 'fa fa-mouse-pointer' },
      {  code: 'fa fa-i-cursor' },
      {  code: 'fa fa-object-group' },
      {  code: 'fa fa-object-ungroup' },
      {  code: 'fa fa-sticky-note' },
      {  code: 'fa fa-sticky-note-o' },
      {  code: 'fa fa-cc-jcb' },
      {  code: 'fa fa-cc-diners-club' },
      {  code: 'fa fa-clone ' },
      {  code: 'fa fa-balance-scale' },
      {  code: 'fa fa-hourglass-o' },
      {  code: 'fa fa-hourglass-1' },
      {  code: 'fa fa-hourglass-start' },
      {  code: 'fa fa-hourglass-2' },
      {  code: 'fa fa-hourglass-half' },
      {  code: 'fa fa-hourglass-3' },
      {  code: 'fa fa-hourglass-end' },
      {  code: 'fa fa-hourglass ' },
      {  code: 'fa fa-hand-grab-o' },
      {  code: 'fa fa-hand-rock-o' },
      {  code: 'fa fa-hand-stop-o' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-hand-paper-o' },
      {  code: 'fa fa-hand-scissors-o' },
      {  code: 'fa fa-hand-lizard-o ' },
      {  code: 'fa fa-hand-spock-o' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-hand-pointer-o' },
      {  code: 'fa fa-hand-peace-o' },
      {  code: 'fa fa-trademark ' },
      {  code: 'fa fa-registered ' },
      {  code: 'fa fa-creative-commons ' },
      {  code: 'fa fa-gg ' },
      {  code: 'fa fa-gg-circle' },
      {  code: 'fa fa-tripadvisor ' },
      {  code: 'fa fa-odnoklassniki ' },
      {  code: 'fa fa-odnoklassniki-square' },
      {  code: 'fa fa-get-pocket ' },
      {  code: 'fa fa-wikipedia-w' },
      {  code: 'fa fa-safari ' },
      {  code: 'fa fa-chrome ' },
      {  code: 'fa fa-firefox ' },
      {  code: 'fa fa-opera ' },
      {  code: 'fa fa-internet-explorer' },
      {  code: 'fa fa-tv' },
      {  code: 'fa fa-television ' },
      {  code: 'fa fa-contao' },
      {  code: 'fa fa-500px ' },
      {  code: 'fa fa-amazon ' },
      {  code: 'fa fa-calendar-plus-o' },
      {  code: 'fa fa-calendar-minus-o' },
      {  code: 'fa fa-calendar-times-o' },
      {  code: 'fa fa-calendar-check-o' },
      {  code: 'fa fa-industry ' },
      {  code: 'fa fa-map-signs' },
      {  code: 'fa fa-map-pin' },
      {  code: 'fa fa-arrow-down' },
      {  code: 'fa fa-map-o' },
      {  code: 'fa fa-map ' },
      {  code: 'fa fa-commenting ' },
      {  code: 'fa fa-commenting-o' },
      {  code: 'fa fa-houzz ' },
      {  code: 'fa fa-vimeo ' },
      {  code: 'fa fa-black-tie' },
      {  code: 'fa fa-fonticons ' },
      {  code: 'fa fa-reddit-alien' },
      {  code: 'fa fa-edge ' },
      {  code: 'fa fa-credit-card-alt' },
      {  code: 'fa fa-codiepie ' },
      {  code: 'fa fa-modx ' },
      {  code: 'fa fa-fort-awesome' },
      {  code: 'fa fa-usb ' },
      {  code: 'fa fa-product-hunt ' },
      {  code: 'fa fa-mixcloud' },
      {  code: 'fa fa-scribd ' },
      {  code: 'fa fa-pause-circle ' },
      {  code: 'fa fa-pause-circle-o ' },
      {  code: 'fa fa-stop-circle ' },
      {  code: 'fa fa-stop-circle-o' },
      {  code: 'fa fa-shopping-bag' },
      {  code: 'fa fa-shopping-basket' },
      {  code: 'fa fa-hashtag ' },
      {  code: 'fa fa-bluetooth ' },
      {  code: 'fa fa-bluetooth-b' },
      {  code: 'fa fa-percent ' },
      {  code: 'fa fa-gitlab ' },
      {  code: 'fa fa-wpbeginner ' },
      {  code: 'fa fa-wpforms ' },
      {  code: 'fa fa-envira ' },
      {  code: 'fa fa-universal-access' },
      {  code: 'fa fa-wheelchair-alt' },
      {  code: 'fa fa-question-circle-o ' },
      {  code: 'fa fa-blind ' },
      {  code: 'fa fa-audio-description' },
      {  code: 'fa fa-volume-control-phone' },
      {  code: 'fa fa-braille ' },
      {  code: 'fa fa-assistive-listening-systems' },
      {  code: 'fa fa-asl-interpreting ' },
      {  code: 'fa fa-american-sign-language-interpreting' },
      {  code: 'fa fa-deafness ' },
      {  code: 'fa fa-hard-of-hearing' },
      {  code: 'fa fa-deaf ' },
      {  code: 'fa fa-glide ' },
      {  code: 'fa fa-glide-g' },
      {  code: 'fa fa-signing ' },
      {  code: 'fa fa-sign-language' },
      {  code: 'fa fa-low-vision' },
      {  code: 'fa fa-viadeo ' },
      {  code: 'fa fa-viadeo-square ' },
      {  code: 'fa fa-snapchat ' },
      {  code: 'fa fa-snapchat-ghost ' },
      {  code: 'fa fa-snapchat-square ' },
      {  code: 'fa fa-pied-piper' },
      {  code: 'fa fa-first-order' },
      {  code: 'fa fa-yoast ' },
      {  code: 'fa fa-themeisle ' },
      {  code: 'fa fa-google-plus-circle' },
      {  code: 'fa fa-google-plus-official' },
      {  code: 'fa fa-fa ' },
      {  code: 'fa fa-font-awesome' },
      {  code: 'fa fa-handshake-o' },
      {  code: 'fa fa-envelope-open' },
      {  code: 'fa fa-envelope-open-o' },
      {  code: 'fa fa-linode ' },
      {  code: 'fa fa-address-book' },
      {  code: 'fa fa-address-book-o ' },
      {  code: 'fa fa-vcard ' },
      {  code: 'fa fa-address-card' },
      {  code: 'fa fa-vcard-o' },
      {  code: 'fa fa-address-card-o' },
      {  code: 'fa fa-user-circle ' },
      {  code: 'fa fa-user-circle-o' },
      {  code: 'fa fa-user-o' },
      {  code: 'fa fa-id-badge ' },
      {  code: 'fa fa-drivers-license' },
      {  code: 'fa fa-id-card' },
      {  code: 'fa fa-drivers-license-o ' },
      {  code: 'fa fa-id-card-o ' },
      {  code: 'fa fa-quora ' },
      {  code: 'fa fa-free-code-camp' },
      {  code: 'fa fa-telegram ' },
      {  code: 'fa fa-thermometer-4' },
      {  code: 'fa fa-thermometer' },
      {  code: 'fa fa-thermometer-full' },
      {  code: 'fa fa-thermometer-3' },
      {  code: 'fa fa-thermometer-three-quarters' },
      {  code: 'fa fa-thermometer-2' },
      {  code: 'fa fa-thermometer-half' },
      {  code: 'fa fa-thermometer-1' },
      {  code: 'fa fa-thermometer-quarter' },
      {  code: 'fa fa-thermometer-0' },
      {  code: 'fa fa-thermometer-empty ' },
      {  code: 'fa fa-shower ' },
      {  code: 'fa fa-bathtub ' },
      {  code: 'fa fa-s15 ' },
      {  code: 'fa fa-bath ' },
      {  code: 'fa fa-podcast ' },
      {  code: 'fa fa-window-maximize' },
      {  code: 'fa fa-window-minimize' },
      {  code: 'fa fa-window-restore ' },
      {  code: 'fa fa-times-rectangle' },
      {  code: 'fa fa-window-close' },
      {  code: 'fa fa-times-rectangle-o' },
      {  code: 'fa fa-window-close-o ' },
      {  code: 'fa fa-bandcamp ' },
      {  code: 'fa fa-grav ' },
      {  code: 'fa fa-etsy ' },
      {  code: 'fa fa-imdb ' },
      {  code: 'fa fa-ravelry ' },
      {  code: 'fa fa-eercast ' },
      {  code: 'fa fa-microchip ' },
      {  code: 'fa fa-snowflake-o' },
      {  code: 'fa fa-superpowers ' },
      {  code: 'fa fa-wpexplorer ' },
      {  code: 'fa fa-meetup ' },
    ];
  }
  ngOnInit(): void {
    this.classIcon = this.itemCode?.trim();
  }
  outSelectValue() {
    this.eventSelectValue.emit(this.classIcon);
  }
}
